server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/673161863-beinuan/spring-cloud-config-center.git
          search-paths:
            - spring-cloud-config-center
      label: master

# RabbitMQ配置信息
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    port: 5672

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: cloud-config-center-3344
